spring:
  application:
    name: 40-SB-MS-Cloud-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamalesiddhesh/configuration_properties.git
          default-label: master
          clone-on-start: true
          

management:
  security:
    enabled: false
