eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
  
spring:
  application:
    name: Welcome-API
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8081/
        url: http://localhost:1111/
