spring:
  application:
    name: Greet-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
        instance: 
          management-base-url: http://localhost:9091/

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:      
    health:
      show-details: always